definitions:
  dto.CopyRequest:
    properties:
      fromId:
        type: integer
      fromTopic:
        type: string
      key:
        type: string
      podName:
        type: string
      toId:
        type: integer
      toTopic:
        type: string
    type: object
  dto.PartitionRequest:
    properties:
      clusterId:
        type: integer
      groupId:
        type: string
      ignoredPartitions:
        items:
          type: integer
        type: array
      key:
        type: string
      podName:
        type: string
      topic:
        type: string
    type: object
  dto.SearchRequest:
    properties:
      endDate:
        type: integer
      kafkaId:
        type: integer
      key:
        type: string
      metadataKey:
        type: string
      podName:
        type: string
      startDate:
        type: integer
      topic:
        type: string
      value:
        type: string
      valueType:
        type: integer
    type: object
info:
  contact: {}
paths:
  /master:
    delete:
      consumes:
      - application/json
      parameters:
      - description: pod name
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /master/copy:
    post:
      consumes:
      - application/json
      parameters:
      - description: CopyRequest
        in: body
        name: podBody
        required: true
        schema:
          $ref: '#/definitions/dto.CopyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /master/getconfig:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /master/getenv:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /master/partition:
    post:
      consumes:
      - application/json
      parameters:
      - description: PartitionRequest
        in: body
        name: podBody
        required: true
        schema:
          $ref: '#/definitions/dto.PartitionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /master/search:
    post:
      consumes:
      - application/json
      parameters:
      - description: SearchRequest
        in: body
        name: podBody
        required: true
        schema:
          $ref: '#/definitions/dto.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
swagger: "2.0"
